spring.application.name=app

spring.config.import=optional:file:../mysql/application-mysql-local.properties

spring.main.web-application-type=none
spring.jpa.hibernate.ddl-auto=none

app.uploads.dir=uploads