spring.application.name=app

# Importar configuración de MySQL
spring.config.import=optional:file:../mysql/application-mysql.properties

# Configuración específica de la aplicación de escritorio
spring.main.web-application-type=none
spring.jpa.hibernate.ddl-auto=none

app.uploads.dir=uploads