
soap.server.host=${SOAP_SERVER_HOST:0.0.0.0}

soap.server.port=${SOAP_SERVER_PORT:8081}

soap.server.context-path=${SOAP_SERVER_CONTEXT_PATH:/soap}

soap.server.base-url=${SOAP_SERVER_BASE_URL:}

server.port=${soap.server.port}
server.servlet.context-path=${soap.server.context-path}
server.address=${soap.server.host}
spring.main.banner-mode=console


spring.datasource.url=jdbc:mysql://localhost:3306/culturarte?zeroDateTimeBehavior=CONVERT_TO_NULL
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.profiles.active=dev