<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.culturarte.com/ws/colaboraciones"
           xmlns:tns="http://www.culturarte.com/ws/colaboraciones"
           xmlns:prop="http://www.culturarte.com/ws/propuestas"

           elementFormDefault="qualified">

    <xs:import namespace="http://www.culturarte.com/ws/propuestas"
               schemaLocation="propuestas.xsd"/>

    <!-- Request y Response para listar colaboraciones -->
    <xs:element name="getColaboracionesPorUsuarioRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nickname" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="getColaboracionesPorUsuarioResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="colaboraciones" type="tns:colaboracionType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Request y Response para una colaboración -->
    <xs:element name="getColaboracionRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nickColaborador" type="xs:string"/>
                <xs:element name="tituloPropuesta" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="getColaboracionResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="colaboracion" type="tns:colaboracionType" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="getColaboracionesSinPagoRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nickColaborador" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="getColaboracionesSinPagoResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="colaboraciones" type="tns:colaboracionType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="registrarPagoRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pago" type="tns:pagoType"/>
                <xs:element name="nickColaborador" type="xs:string"/>
                <xs:element name="tituloPropuesta" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="registrarPagoResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="exito" type="xs:boolean"/>
                <xs:element name="mensaje" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Tipos -->
    <xs:complexType name="colaboracionType">
        <xs:sequence>
            <xs:element name="nickColaborador" type="xs:string"/>
            <xs:element name="propuesta" type="prop:propuestaType"/>
            <xs:element name="fecha" type="xs:string"/>
            <xs:element name="hora" type="xs:string"/>
            <xs:element name="monto" type="xs:float"/>
            <xs:element name="tipoRetorno" type="xs:string"/>
            <xs:element name="pago" type="tns:pagoType" minOccurs="0"/>
            <xs:element name="pagada" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="pagoType">
        <xs:sequence>
            <xs:element name="monto" type="xs:float"/>
            <xs:element name="fechaPago" type="xs:string"/>
            <xs:element name="horaPago" type="xs:string"/>
            <xs:element name="tipoPago" type="xs:string"/>
            <xs:element name="nombreTitular" type="xs:string"/>
            <xs:element name="tipoTarjeta" type="xs:string" minOccurs="0"/>
            <xs:element name="numeroTarjeta" type="xs:string" minOccurs="0"/>
            <xs:element name="fechaVencimiento" type="xs:string" minOccurs="0"/>
            <xs:element name="cvc" type="xs:string" minOccurs="0"/>
            <xs:element name="nombreBanco" type="xs:string" minOccurs="0"/>
            <xs:element name="numeroCuenta" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Alta colaboración -->
    <xs:element name="altaColaboracionRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tituloPropuesta" type="xs:string"/>
                <xs:element name="nickColaborador" type="xs:string"/>
                <xs:element name="monto" type="xs:float"/>
                <xs:element name="tipoRetorno" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="altaColaboracionResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="exito" type="xs:boolean"/>
                <xs:element name="mensaje" type="xs:string" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
