<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.culturarte.com/ws"
           xmlns="http://www.culturarte.com/ws"
           elementFormDefault="qualified">

    <!-- Importar los módulos -->
    <xs:import namespace="http://www.culturarte.com/ws/usuarios"
               schemaLocation="usuarios.xsd"/>

    <xs:import namespace="http://www.culturarte.com/ws/propuestas"
               schemaLocation="propuestas.xsd"/>

    <xs:import namespace="http://www.culturarte.com/ws/categorias"
               schemaLocation="categorias.xsd"/>

    <xs:import namespace="http://www.culturarte.com/ws/colaboraciones"
               schemaLocation="colaboraciones.xsd"/>

    <!-- Puedes dejar definiciones globales si quieres -->
    <xs:element name="pingRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="message" type="xs:string" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="pingResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="message" type="xs:string"/>
                <xs:element name="timestamp" type="xs:dateTime"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

