<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.culturarte.com/ws/propuestas"
           xmlns:tns="http://www.culturarte.com/ws/propuestas"
           elementFormDefault="qualified">

    <xs:element name="listarPropuestasRequest" type="xs:anyType"/>

    <xs:element name="listarPropuestasResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="propuesta" type="tns:propuestaType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="getPropuestaRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="getPropuestaResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="propuesta" type="tns:propuestaType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="propuestaType">
        <xs:sequence>
            <xs:element name="titulo" type="xs:string"/>
            <xs:element name="descripcion" type="xs:string" minOccurs="0"/>
            <xs:element name="proponente" type="xs:string" minOccurs="0"/>
            <xs:element name="categoria" type="xs:string" minOccurs="0"/>
            <xs:element name="estado" type="xs:string" minOccurs="0"/>
            <xs:element name="imagen" type="xs:string" minOccurs="0"/>
            <xs:element name="fechaPrevista" type="xs:date" minOccurs="0"/>
            <xs:element name="montoNecesario" type="xs:float" minOccurs="0"/>
            <xs:element name="montoRecaudado" type="xs:float" minOccurs="0"/>
            <xs:element name="cantColaboradores" type="xs:int" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="listarPropuestasResponse"></xs:complexType>
</xs:schema>
