<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.culturarte.com/ws/usuarios"
           xmlns:tns="http://www.culturarte.com/ws/usuarios"
           elementFormDefault="qualified">

    <xs:element name="getUsuarioRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nickname" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="getUsuarioResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuario" type="tns:usuarioType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="usuarioType">
        <xs:sequence>
            <xs:element name="nickname" type="xs:string"/>
            <xs:element name="nombre" type="xs:string" minOccurs="0"/>
            <xs:element name="apellido" type="xs:string" minOccurs="0"/>
            <xs:element name="email" type="xs:string" minOccurs="0"/>
            <xs:element name="imagen" type="xs:string" minOccurs="0"/>
            <xs:element name="fechaNacimiento" type="xs:date" minOccurs="0"/>
            <xs:element name="tipo" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>
